EMSWebProject/Models/Assets.cs
using System.ComponentModel.DataAnnotations;

namespace EMSWebProject.Models
{
    public class Assets 
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public int PurchasingPrice { get; set; }

        [Required]
        public string Status { get; set; }

        public DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public int? ModifiedBy { get; set; }

    }
}

EMSWebProject/Models/BaseEntity.cs
using System.ComponentModel.DataAnnotations;

namespace EMSWebProject.Models
{
    public class BaseEntity
    {
        [Key]
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public int? ModifiedBy { get; set; }
    }
}

EMSWebProject/Models/EmployeeAssets.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMSWebProject.Models
{
    public class EmployeeAssets
    {
        [Key]
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int AssetId { get; set; }
        public DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public int? ModifiedBy { get; set; }
        public string Remarks { get; set; }

      
    }
}

EMSWebProject/Models/EmployeeInfo.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace EMSWebProject.Models
{
    public class EmployeeInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Designation { get; set; }

        
    }
}

EMSWebProject/Models/ErrorViewModel.cs
namespace EMSWebProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EMSWebProject/Controllers/AssetsController.cs
using EMSWebProject.Interface;
using EMSWebProject.Models;
using EMSWebProject.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EMSWebProject.Controllers
{
    public class AssetsController : Controller
    {
        private readonly IAssetsRepository _assetsRepository;
        public AssetsController(IAssetsRepository assetsRepository)
        {
            _assetsRepository = assetsRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

       
        public  IActionResult AddAssets()
        {
            return View();
        }

        [HttpPost]
        [Route("Assets/AddAssets")]
        public async Task<IActionResult> AddAssets(Assets assets)
        {
           var result =await _assetsRepository.AddAssetsAsync(assets);
            if(result == 0)
            {
                throw new Exception("Record not added");
            }
            return RedirectToAction("GetAssetRecords");
        }

       
       
        public async Task<IActionResult> GetAssetRecords()
        {
            try
            {
                var result = await _assetsRepository.GetAssetRecords();
                if(result == null)
                {
                    throw new Exception();
                }
                return View(result);
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
      
        }

        

        public async Task<IActionResult> GetAssetsRecordById(int id)
        {
            var result = await _assetsRepository.GetAssetsRecordById(id);
            return View(result);
        }

        [HttpPost]
        [Route("Assets/UpdateAssetsRecords")]
      public async Task<IActionResult> UpdateAssetsRecords(Assets assets)
        {
            var result = await _assetsRepository.UpdateAssetsRecords(assets);
            return RedirectToAction("GetAssetRecords");
        }

        
        [Route("Assets/DeleteAssetsRecords/{id}")]
        public async Task<IActionResult> DeleteAssetsRecords(int id)
        {
            var result = await _assetsRepository.DeleteAssetsRecords(id);
            if(result > 0)
            {
              return RedirectToAction("GetAssetRecords");
            }
            return View("AddAssets");
        }

       
        public async Task<IActionResult> AssignAssets()
        {
           var result = await _assetsRepository.EmployeeAssetList();

            return View(result);
        }

        [HttpPost]
        [Route("Assets/AssignAssets")]
        public async Task<IActionResult> AssignAssets(EmployeeAssets employeeAssets)
        {
           var result = await _assetsRepository.AssignEmployeeAsset(employeeAssets);
            if (result > 0) 
            {
                return RedirectToAction("ListAssestWithEmployee");
            }
            return View();
        }

        public async Task<IActionResult> ListAssestWithEmployee(int id)
        {
            
          var result = await  _assetsRepository.ListAssetandEmployee(id);
            return View(result);    
        }
    }
}

EMSWebProject/Controllers/HomeController.cs
using EMSWebProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EMSWebProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EMSWebProject/Views/Assets/AddAssets.cshtml
<form method="post" asp-controller="Assets" asp-action="AddAssets">
    <h2>ADD ASSET</h2>
    <div class="form-group mt-2">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="Name" placeholder="Enter assets Name" required>
    </div>
    <div class="form-group mt-2">
        <label for="exampleInputEmail1">Description</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="Description" placeholder="Enter assets Description" required>
    </div>

    <div class="form-group mt-2">
        <label for="exampleInputEmail1">PurchasingPrice</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="PurchasingPrice" placeholder="Enter assets PurchasingPrice" required>
    </div>

   
    <label class="form-group" for="Status">Status:</label>
    <select class="form-control" name="Status" id="Status" required>
        <option value="New">New</option>
        <option value="Available">Available</option>
        <option value="Reserved">Reserved</option>
        <option value="Assigned">Assigned</option>
        <option value="Unassigned">Unassigned</option>
        <option value="OutOfService">Out Of Service</option>

    </select>
  <div class="form-group mt-2">

    <button type="submit" class="btn btn-primary btn-user btn-block">Submit</button>
  </div>
</form>

EMSWebProject/Views/Assets/AssignAssets.cshtml
@model EMSWebProject.ViewModel.EmployeeAssestViewModel
<form method="post" asp-controller="Assets" asp-action="AssignAssets" >
    <h2>Assign Something</h2>
    <div class="row">
        <div class="col-6">
            <label class="form-group" for="EmployeeId">Select Employee:</label>
            <select class="form-control" name="EmployeeId" id="" required>
                @foreach (var i in Model.Employees)
                {
                    <option value="@i.Id">@i.Name</option>
                }
            </select>
        </div>
        <div class="col-6">
            <label class="form-group" for="AssetId">Assign Asset:</label>
            <select class="form-control" name="AssetId" id="" required>
                @foreach (var i in Model.Assets)
                {
                    <option value="@i.Id">@i.Name</option>
                }
            </select>
        </div>

    </div>

    <div class="row">
        <div class="form-group mt-2">
            <label for="exampleInputEmail1">Remarks</label>
            <input type="text" class="form-control" id="" aria-describedby="emailHelp" value="" name="Remarks" placeholder="Enter assets Remarks" required>
        </div>
    </div>
   
    <hr />

    <div class="form-group mt-2">

        <button type="submit" class="btn btn-primary btn-user btn-block">Submit</button>
    </div>
</form>

EMSWebProject/Views/Assets/GetAssetRecords.cshtml
@model IEnumerable<EMSWebProject.Models.Assets>
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <button class="btn btn-success"> <a href="/Assets/AddAssets" class="text-light">Add Asset</a></button>

                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Purchasing Price</th>
                            <th>Status</th>
                            <th>CreatedAt </th>
                            <th>CreatedBy</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Purchasing Price</th>
                            <th>Status</th>
                            <th>CreatedAt </th>
                            <th>CreatedBy</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach(var i in Model)
                        {
                            <tr>
                                <td style="display : none">@i.Id</td> 
                                <td>@i.Name</td>
                                <td>@i.Description</td>
                                <td>@i.PurchasingPrice</td>
                                <td><a href="/Assets/ListAssestWithEmployee/@i.Id">@i.Status</a></td>
                                <td>@i.CreatedAt</td>
                                <td>@i.CreatedBy</td>
                                <td>
                                    <button class="btn btn-success"> <a href="/Assets/GetAssetsRecordById/@i.Id" class="text-light">Edit</a></button>
                                    <button class="btn btn-danger"> <a href="/Assets/DeleteAssetsRecords/@i.Id" class="text-light">Delete</a></button>
                                </td>
                            </tr>
                        }
                        
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

EMSWebProject/Views/Assets/GetAssetsRecordById.cshtml
@model EMSWebProject.Models.Assets






<form method="post" asp-controller="Assets" asp-action="UpdateAssetsRecords">

    <input type="text" class="form-control" hidden id="" aria-describedby="emailHelp" value="@Model.Id" name="Id" placeholder="Enter assets Name">

    <div class="form-group mt-2">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" value="@Model.Name" name="Name" placeholder="Enter assets Name">
    </div>
    <div class="form-group mt-2">
        <label for="exampleInputEmail1">Description</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" value="@Model.Description" name="Description" placeholder="Enter assets Description">
    </div>

    <div class="form-group mt-2">
        <label for="exampleInputEmail1">PurchasingPrice</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" value="@Model.PurchasingPrice" name="PurchasingPrice" placeholder="Enter assets PurchasingPrice">
    </div>

    <div class="form-group mt-2">
        <label for="exampleInputEmail1">Status</label>
        <input type="text" class="form-control" id="" aria-describedby="emailHelp" value="@Model.Status" name="Status" placeholder="Enter assets Status">
    </div>

    <div class="form-group mt-2">

        <button type="submit" class="btn btn-primary btn-user btn-block">Submit</button>
    </div>
</form>

EMSWebProject/Views/Assets/ListAssestWithEmployee.cshtml
@model IEnumerable<EMSWebProject.ViewModel.ListEmployeeAssetViewModel>
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <button class="btn btn-success"> <a href="/Assets/AddAssets" class="text-light">Add Asset</a></button>

                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Purchasing Price</th>
                            <th>Status</th>
                            <th>Assign TO</th>
                            <th>CreatedAt </th>
                            <th>CreatedBy</th>
                           
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Purchasing Price</th>
                            <th>Status</th>
                            <th>Assign To</th>
                            <th>CreatedAt </th>
                            <th>CreatedBy</th>
                          
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var i in Model)
                        {
                            <tr>
                                <td style="display : none">@i?.Id</td>
                                <td>@i.Asset_Name</td>
                                <td>@i.Description</td>
                                <td>@i.PurchasingPrice</td>
                                <td>@i.Status</td>
                                <td>@i.Emp_Name</td>
                                <td>@i.CreatedAt</td>
                                <td>@i.CreatedBy</td>
                               @*  <td>
                                    <button class="btn btn-success"> <a href="/Assets/GetAssetsRecordById/@i.Id" class="text-light">Edit</a></button>
                                    <button class="btn btn-danger"> <a href="/Assets/DeleteAssetsRecords/@i.Id" class="text-light">Delete</a></button>
                                </td> *@
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

EMSWebProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-dark-menu sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/Home/Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>
          
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Assets</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-dark-mode py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Assets Details:</h6>
                        <a class="collapse-item" href="/Assets/ListAssestWithEmployee">List Of Asssigned Asset</a>
                        <a class="collapse-item" href="/Assets/AddAssets">Add Asset</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Asset Management</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-dark-mode py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Assign Asset to Employee :</h6>
                        <a class="collapse-item" href="/Assets/AssignAssets">Asset Assign</a>
                        <a class="collapse-item" href="/Assets/GetAssetRecords">Basic Assets Info</a>
                        <a class="collapse-item" href="">Other Info</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-dark-mode py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Login Screens:</h6>
                        <a class="collapse-item" href="login.html">Login</a>
                        <a class="collapse-item" href="register.html">Register</a>
                        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                        <div class="collapse-divider"></div>
                        <h6 class="collapse-header">Other Pages:</h6>
                        <a class="collapse-item" href="404.html">404 Page</a>
                        <a class="collapse-item" href="blank.html">Blank Page</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span>
                </a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="/img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2">
                    <strong>SB Admin Pro</strong> is packed with premium features, components,
                    and more!
                </p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">
                    Upgrade to
                    Pro!
                </a>
            </div>

        </ul>

        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <div>
            @RenderSection("scripts", required: false)
        </div>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
      
        <!-- End of Content Wrapper -->
        

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/js/demo/chart-area-demo.js"></script>
    <script src="/js/demo/chart-pie-demo.js"></script>

</body>

</html>




















@* ------------------------------------------------------------------ *@

@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMSWebProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMSWebProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMSWebProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="AddAssets">Add Assets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="GetAssetRecords">Get Asset Records</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="AssignAssets">Assign Asset </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="ListAssestWithEmployee">ListOfAsssignedAsset </a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EMSWebProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 *@